import Ionicons from "react-native-vector-icons/Ionicons";

export const amenityIconMap = {
  AC: "snow-outline",
  TV: "tv-outline",
  "Modern Wardrobe": "shirt-outline",
  "Free Wifi": "wifi-outline",
  Kitchen: "restaurant-outline",
  "King Sized Bed": "bed-outline",
  "Swimming Pool": "water-outline",
  "Attached Washroom": "water-outline",
  "Seating Area": "business-outline",
  "Power Backup": "flash-outline",
  Geyser: "thermometer-outline",
  "Parking Facility": "car-outline",
  "Electric Kettle": "cafe-outline",
  Elevator: "swap-vertical-outline",
  "Room Heater": "flame-outline",
  Restaurant: "restaurant-outline",
  "Card Payment": "card-outline",
  "CCTV Cameras": "videocam-outline",
  Reception: "person-outline",
  "24/7 Check-In": "time-outline",
  "Dress Hanger": "shirt-outline",
  Toaster: "fast-food-outline",
  "Daily Housekeeping": "broom-outline",
  Safe: "lock-closed-outline",
  Iron: "hammer-outline",
  "First-aid kit": "medkit-outline",
  "Smoking Room": "smoking-outline",
  "Bedside Table": "cube-outline",
  "Fire extinguisher": "flame-outline",
  "Security Guard": "shield-checkmark-outline",
  "More": "chevron-down-outline",
  "Less": "chevron-up-outline",
};
